name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies MyLanguage/MyLanguage.sln
      run: dotnet restore MyLanguage/MyLanguage.sln
    - name: Build
      run: dotnet build MyLanguage/MyLanguage.sln --no-restore
    - name: Test
      run: dotnet test MyLanguage/MyLanguage.sln --no-build --verbosity normal
